### ISSUE TITLE
Fct réalisées et itération 2

### ISSUE THREAD

**Issue by oliviercailloux** [LoatR/AssistedBoardGames#3]
ShowClient, dans votre Itération 1 dans le cahier des charges actuellement visible sur master, ne décrit pas bien ce que vous avez fait. Votre code ne "show" pas grand-chose, actuellement. Il s’agit plutôt de servlets, j’imagine, dont vous vouliez parler là. Veuillez modifier la description. Vous pouvez le faire directement sur la branche master.
Veuillez modifier l’itération 2, par la même occasion :
- passage à du JPA plus propre (injection de l’entity manager, gestion automatique des transactions par le conteneur)
- ObjectsXml à supprimer, on a déjà plein de façons de représenter l’état. Il serait bon, à la place, que vos servlets acceptent également les formats standards existant pour représenter un coup ou un état d’une partie (mais ce n’est pas une priorité absolue, bien que cela ne devrait pas être très difficile).
- Votre fct Player pourrait être trop ambitieuse, mais vous pouvez décider en le faisant. Si vous faites ce qui est annoncé avec une belle interface graphique, ça vaut nettement plus qu’un point de difficulté. Simplifiez si nécessaire avec une interface graphique minimaliste, éventuellement en permettant simplement de taper au clavier le coup souhaité. NB rien ne vous empêche d’utiliser une autre bibliothèque que vous aviez trouvée si elle peut vous aider pour l’affichage graphique, en plus de celle sur laquelle vous êtes partis.

**Comment by ThibaudduSartel** [comment]
Bonsoir Monsieur, @oliviercailloux ,

Nous avons pris la décision suivante concernant l'itération 2, merci de nous dire si cela vous convient.

La fonctionnalité "Player" (tâche 3) a été allégée. La représentation graphique sur le client sera minimaliste, c'est-à-dire qu'elle utilisera la représentation du plateau fournie par la bibliothèque sous forme de String. Le niveau de difficulté devrait donc correspondre plus 

Nous avons supprimé la tâche Object XML (tâche 2), et ajouté une tâche de l'itération 3 à l'itération 2 (Tâche Help, qui est maintenant la tâche 6 de l'itération 2).

Nous envisageons, pour compenser ce manque dans l'itération 3, d'ajouter une tâche qui permettra soit d'afficher un coup à l'aide d'une interface graphique, soit de permettre aux servlets d'accepter les formats standards existants.

**Comment by oliviercailloux** [comment]
Ok. Communiquer via les formats standards me semble plus prioritaire qu’une interface graphique.
Supprimez ce qui est noté comme SUPPRIMÉ, on y verra plus clair.
