### ISSUE TITLE
Use delimited identifiers

### ISSUE THREAD

**Issue by oliviercailloux** [LoatR/AssistedBoardGames#5]
J’ai soumis un rapport de bug ([HHH-13347](https://hibernate.atlassian.net/browse/HHH-13347)) à Hibernate concernant le fichier `orm.xml`.

Veuillez ajouter la proporiété indiquée à votre persistence.xml, avec un commentaire indiquant un lien vers ce rapport de bug, et restaurer le nom “from” dans votre code source, en vérifiant que Hibernate délimite bien les identifiants SQL.

Fermez cette issue si ça fonctionne, sinon, me l’indiquer SVP.

**Comment by MeganBr** [comment]
Bonjour Monsieur, 
Nous avons modifié le persistence.xml et restauré le nom "from" et cela fonctionne. 
Merci beaucoup
